baseURL = "https://jsell-rh.github.io/blog/"
languageCode = "en-us"
theme = "re-terminal"
pagination.pagerSize = 10

[params]
  contentTypeName = "posts"
  themeColor = "paper"
  fullWidthTheme = false
  centerTheme = true
  readingTime = true
  showMenuItems = 2

[params.logo]
  logoText = "john sell"
  logoHomeLink = "/"

[params.footer]
  customFooter = "*All views and opinions expressed here are my own and do not represent those of my employer.*"

[languages.en.params]
  title = "John Sell"
  subtitle = "Thinking about the future of fully autonomous software development."
  keywords = "blog, autonomous development, gyre"
  copyright = ""
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
