baseURL = "https://jsell-rh.github.io/blog/"
languageCode = "en-us"
title = "John Sell"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "Thoughts and opinions from my brain to yours."
  author = "John Sell"
  defaultTheme = "light"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  disableSpecial1stPost = false
  comments = true

  [params.homeInfoParams]
    Title = "My Thoughts and Opinions"
    Content = """I'm thinking a lot about how the software development lifecycle will evolve in the age of AI.<br/>I expect my thoughts and opinions will age like milk, but I hope that sharing them here may be of some help to you. <br/><br/>*All views and opinions expressed here are my own and do not represent those of my employer.*"""

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jsell-rh"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
