baseURL = "https://jsell-rh.github.io/blog/"
languageCode = "en-us"
title = "John Sell"
theme = "PaperMod"
[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "Thoughts on autonomous software development"
  author = "John Sell"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  defaultTheme = "auto"
  disableSpecial1stPost = false

  [params.homeInfoParams]
    Title = "John Sell"
    Content = """Thinking about the future of fully autonomous software development.\n\n*All views and opinions expressed here are my own and do not represent those of my employer.*"""

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jsell-rh"

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
